"""
FactoryGuard AI - Behaviour & Safety Reasoning Analyzer

Phase 2: Behaviour and Safety Intelligence Layer

Combines spatial zone events, dwell time state, and worker PPE status to evaluate
safety compliance and generate structured safety incidents.

Safety Reasoning Rules:
    - Restricted Zone Entry       -> HIGH Severity
    - Restricted Zone Dwell (>5s) -> CRITICAL Severity
    - Warning Zone Entry          -> WARNING Severity
    - Warning Zone Dwell (>10s)   -> WARNING Severity
    - PPE Violation in Zone       -> CRITICAL Severity (if PPE detected missing)
"""

import os
import logging
from typing import List, Optional, Any
import numpy as np

from behaviour.zone_manager import Zone, ZoneType
from behaviour.zone_detector import ZoneEvent, EventType
from behaviour.ppe_interface import PPEInterface, WorkerPPEState
from behaviour.incident_manager import IncidentManager, SafetyIncident, Severity
from behaviour.evidence import EvidenceManager

logger = logging.getLogger("factoryguard.behaviour.behaviour_analyzer")


class BehaviourAnalyzer:
    """Core safety intelligence engine evaluating spatial events and generating incidents.

    Args:
        incident_manager: IncidentManager instance.
        evidence_manager: EvidenceManager instance.
        ppe_interface: PPEInterface instance.
    """

    def __init__(
        self,
        incident_manager: Optional[IncidentManager] = None,
        evidence_manager: Optional[EvidenceManager] = None,
        ppe_interface: Optional[PPEInterface] = None,
    ):
        self.incident_manager = incident_manager or IncidentManager()
        self.evidence_manager = evidence_manager or EvidenceManager()
        self.ppe_interface = ppe_interface or PPEInterface()

    def process_frame_events(
        self,
        events: List[ZoneEvent],
        frame: Optional[np.ndarray],
        zones: List[Zone],
    ) -> List[SafetyIncident]:
        """Analyze frame events, apply safety rules, and record incidents.

        Args:
            events: List of ZoneEvent instances generated by ZoneDetector for this frame.
            frame: Optional BGR NumPy image array for evidence capture.
            zones: List of active Zone instances.

        Returns:
            List of newly created SafetyIncident instances.
        """
        created_incidents: List[SafetyIncident] = []

        for event in events:
            # Query PPE status
            ppe_state = self.ppe_interface.get_worker_ppe(
                event.worker_id, frame=frame, bbox=event.worker_bbox
            )
            ppe_dict = ppe_state.to_dict()

            # Rule evaluation
            severity = Severity.WARNING.value
            description = ""
            should_create_incident = True

            if event.event_type == EventType.RESTRICTED_ENTRY.value:
                severity = Severity.HIGH.value
                description = f"Worker {event.worker_id} entered RESTRICTED zone '{event.zone_name}'."
                if ppe_state.helmet is False or ppe_state.vest is False:
                    severity = Severity.CRITICAL.value
                    description += " (PPE VIOLATION DETECTED)"

            elif event.event_type == EventType.RESTRICTED_DWELL.value:
                severity = Severity.CRITICAL.value
                description = (
                    f"Worker {event.worker_id} PROLONGED RESTRICTED PRESENCE "
                    f"({event.dwell_time:.1f}s) in zone '{event.zone_name}'."
                )

            elif event.event_type == EventType.WARNING_ENTRY.value:
                severity = Severity.WARNING.value
                description = f"Worker {event.worker_id} entered WARNING zone '{event.zone_name}'."

            elif event.event_type == EventType.WARNING_DWELL.value:
                severity = Severity.WARNING.value
                description = (
                    f"Worker {event.worker_id} sustained presence ({event.dwell_time:.1f}s) "
                    f"in warning zone '{event.zone_name}'."
                )

            else:
                # Entry/Exit events that do not warrant alert incidents
                should_create_incident = False

            if should_create_incident:
                # Capture visual evidence snapshot
                evidence_path = ""
                if frame is not None:
                    # Temporary incident ID placeholder
                    temp_inc_id = f"INC-TEMP-{event.worker_id}"
                    evidence_path = self.evidence_manager.capture_evidence(
                        frame=frame,
                        incident_id=temp_inc_id,
                        worker_id=event.worker_id,
                        event=event.event_type,
                        timestamp=event.timestamp,
                        frame_number=event.frame,
                        zone_name=event.zone_name,
                        severity=severity,
                        worker_bbox=event.worker_bbox,
                        zones=zones,
                        description=description,
                    )

                # Register incident (handles deduplication cooldowns)
                incident = self.incident_manager.create_incident(
                    worker_id=event.worker_id,
                    event=event.event_type,
                    timestamp=event.timestamp,
                    frame=event.frame,
                    zone=event.zone_name,
                    severity=severity,
                    description=description,
                    dwell_time=event.dwell_time,
                    ppe_status=ppe_dict,
                    worker_bbox=event.worker_bbox,
                    worker_center=event.worker_center,
                    evidence_frame_path=evidence_path,
                )

                if incident:
                    # Rename evidence snapshot with final incident_id if captured
                    if evidence_path and os.path.isfile(evidence_path):
                        final_path = evidence_path.replace("INC-TEMP-", f"{incident.incident_id}_")
                        try:
                            os.replace(evidence_path, final_path)
                            incident.evidence_frame_path = final_path
                        except Exception as e:
                            logger.warning("Could not rename evidence snapshot: %s", e)

                    created_incidents.append(incident)

        return created_incidents
